# Generated by Django 4.1.3 on 2023-05-04 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='table',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
