# Generated by Django 4.1.3 on 2023-05-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_cart_current_orders_delete_books_delete_issued_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10)),
                ('items', models.CharField(max_length=1000)),
                ('paymentmode', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
