# Generated by Django 4.1.3 on 2023-05-05 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_completed_orders_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_orders',
            name='table',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
