# Generated by Django 4.1.3 on 2023-05-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_current_orders_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed_orders',
            name='total_payment',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
