# Generated by Django 4.1.3 on 2023-05-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_completed_orders_total_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed_orders',
            name='date',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
